@startuml

left to right direction

actor Student
actor Instructor
actor Admin

package "UpSkillz" {
    usecase "Browse Courses" as UC1
    usecase "Enroll in a Course" as UC2
    usecase "See Learning history" as UC11
    usecase "Leave a Review" as UC5
    usecase "Login/Register" as UC10

    usecase "Create a Course" as UC6
    usecase "Manage Lessons" as UC7
    usecase "Update Course Information" as UC8

    usecase "Manage Users" as UC9
    usecase "See statistics" as UC12
}

Student --> UC1
Student --> UC2
Student --> UC11
Student --> UC5
Student --> UC10

Instructor --> UC10
Instructor --> UC6
Instructor --> UC7
Instructor --> UC8

Admin --> UC9
Admin --> UC12

@enduml
